import type { Metadata } from 'next';
import { ClerkProvider } from '@clerk/nextjs';
import { AppContent } from '@/components/layout/AppContent';
import './globals.css';

export const metadata: Metadata = {
  title: 'voxproc',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="antialiased bg-white text-zinc-900">
          <AppContent>{children}</AppContent>
        </body>
      </html>
    </ClerkProvider>
  );
}
